name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run the application
        run: java -Dspring.profiles.active=test -jar app-ibank-build-for-testers.jar &

      - name: Wait until server is up
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: 'http://localhost:9999'
          timeout: 30

      - name: Run tests
        run: ./gradlew test --info
